### PR TITLE
Reorganise into theme modules & common code

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by jasonm23** [comment]
Installs locally from loading tao-yin-theme, tao-yang-theme, tao-yinyang-common with `M-x load-file` and then `M-x load-theme` `tao-yin` or `tao-yang`

**Comment by jasonm23** [comment]
We may be able to lose the file `tao-theme.el` - I was following the pattern of `apropospriate` but I think that file is redundant.

**Comment by 11111000000** [comment]
wow,thank you!

**Comment by jasonm23** [comment]
You're welcome

**Comment by jasonm23** [comment]
By the way, I reimplemented your palette loops using cl-loop.  

This means you'll may need to add a dependency on (and require) (cl-lib "0.5")

**Pull request merged**
